spring:
  redis:
    database: 0 #Redis数据库索引（默认为0）
    port: 6379 #端口号
#    password:  #输入redis数据库密码
    host: localhost    #输入ip地址
    # 第二种方法
    client-type: jedis
    ######   Jedis------------Jedis 和 Lettuce 二选一
    jedis:
      pool:
        max-idle: 6    #最大空闲数
        max-active: 10 #最大连接数
        min-idle: 2    #最小空闲数
        max-wait: -1ms #最大阻塞等待时间负数表示没有等待时间
    timeout: 2000   #连接超时
    ######   Lettuce
    lettuce:
      pool:
        max-active: 10  #最大连接数
        max-idle: 10 #最大空闲连接数
        min-idle: 0 #最小空闲连接数
        max-wait: -1ms #最大阻塞等待时间负数表示没有等待时间

